# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-10 20:05
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=255)),
                ('osm_id', models.PositiveIntegerField(unique=True)),
                ('place_id', models.PositiveIntegerField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('osm_type', models.IntegerField(choices=[(0, b'None'), (1, b'Node'), (2, b'Way'), (3, b'Relation')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PlacePolygon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polygon', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('simplicity', models.IntegerField(default=0)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polygons', to='geomap.Place')),
            ],
        ),
    ]
