# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-11 18:21

# Trouble with saving place id since the integer is larger than what is
# available in PositiveIntegerField
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geomap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='osm_id',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='place_id',
            field=models.BigIntegerField(),
        ),
    ]
